### ISSUE TITLE
Boa locks on unfinished syntax

### ISSUE THREAD

**Issue by yeyande** [JacobAMason/Boa#2]
If a user supplies a single quote, double quote, or open parenthesis, it will lock up because the command was never completed.

**Comment by JacobAMason** [comment]
Can you detail how to reproduce this? I can't seem to recreate this bug.

**Comment by yeyande** [comment]
Ignore this. I realized that eval will do this check prior to it running. I just saw Boa stop responding after people used apostrophe's and assumed that was the issue
